#! /bin/sh

source ~/.config/global.conf

bspc config top_padding                 0
bspc config left_padding                0
bspc config right_padding               0
bspc config bottom_padding              0
bspc config border_width                0
bspc config window_gap                  5
bspc config split_ratio                 0.5
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config single_monocle              true
bspc config focus_follows_pointer       false
bspc config pointer_follows_monitor     false
bspc config pointer_follows_focus       false
bspc config focus_by_distance           true
bspc config click_to_focus              true
bspc config focused_border_color        $GREY
bspc config unfocused_border_color      $BAR_BG
bspc config presel_feedback_color       $BLUE
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true

bspc rule -a Gpick state=floating
bspc rule -a Leafpad state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a rofi manage=off
bspc rule -a Galculator state=floating

desktops=$(bspc query --monitors)

if [[ $(echo "$desktops" | wc -l) -eq 3 ]]; then
    bspc monitor ^2 -s ^3
fi

# Create desktops
i=1
for monitor in $desktops; do
        bspc monitor "$monitor" -d $i/{i,ii,iii,iv,v}
    let i++
done
