#! /bin/sh

source ~/.config/global.conf

bspc config top_padding             20
bspc config left_padding            0
bspc config right_padding           0
bspc config bottom_padding          0
bspc config border_width            1
bspc config window_gap              5
bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   false
bspc config pointer_follows_monitor false
bspc config pointer_follows_focus   false
bspc config focus_by_distance       true
bspc config focused_border_color    $BLUE
bspc config unfocused_border_color  $GREY

bspc rule -a gpick floating=on

desktops=$(bspc query --monitors)

if [[ $(echo "$desktops" | wc -l) -eq 3 ]]; then
    bspc monitor ^2 -s ^3
fi

# Create desktops
i=1
for monitor in $desktops; do
        bspc monitor "$monitor" -d $i/{i,ii,iii,iiii,iiiii}
    let i++
done

killall panel
~/.scripts/panel &
