#!/bin/sh
source ~/.config/global.conf

batt_file=/sys/class/power_supply/BAT0/capacity
batt_level=$(cat $batt_file)
batt_status=$(cat /sys/class/power_supply/BAT0/status)

battery() {
    if [ -f $batt_file ]; then
        if [ $batt_status == 'Charging'  ] && [ $batt_level -gt 98 ] ; then
            popup -e "$(echo " $batt_level")" -W 75 -b "$GREEN" -f "$DARK_GREY"
        elif [ $batt_status == 'Charging' ] ; then
            popup -e "$(echo " $batt_level")" -w 75 -b "$BLUE" -f "$DARK_GREY"
        elif [ $batt_level -le 10 ] ; then
            popup -e "$(echo " $batt_level")" -w 75 -s 60 -b "$RED"
        elif [ $batt_level -lt 50 ] ; then
            popup -e "$(echo " $batt_level")" -w 75
        elif [ $batt_level -le 100 ] ; then
            popup -e "$(echo " $batt_level")" -w 75
        fi
    fi
}

battery
