#!/bin/bash
bspc subscribe monitor | while read -r line; do
  case $line in
      monitor_add*|monitor_geometry*)
        if [ "$(bspc query -M | wc -l)" -eq "3" ]; then
          bspc monitor $(bspc query -M | sed -n 1p) -d 1/{i,ii,iii}
          bspc monitor $(bspc query -M | sed -n 2p) -d 2/{i,ii,iii}
          bspc monitor $(bspc query -M | sed -n 3p) -d 3/{i,ii,iii}
        elif [ "$(bspc query -M | wc -l)" -eq "2" ]; then
          bspc monitor $(bspc query -M | sed -n 1p) -d 1/{i,ii,iii,iv}
          bspc monitor $(bspc query -M | sed -n 2p) -d 2/{i,ii,iii,iv}
        else
          bspc monitor -d 1/{i,ii,iii,iv,v,vi}
        fi
        ;;
      *)
      ;;
  esac
done &
