#!/bin/sh

source ~/.config/global.conf
source ~/.scripts/monitor-center

# Get centered dimensions based on display resolution
for RES in $SR
do
    center_object $RES
done

DMENU_PROMPT='>>'
DMENU_FN=$FONT1
DMENU_DIM=0.3

DMENU_NORMBG=$BAR_BG
DMENU_NORMFG=$BAR_FG
DMENU_SELBG=$BLUE
DMENU_SELFG=$WHITE

DMENU_WIDTH=300
DMENU_HEIGHT=20
DMENU_X=$(($PX - $DMENU_WIDTH/2))
DMENU_Y=$(($PY - $DMENU_HEIGHT/2))
DMENU_LINES=3

dmenu_run \
    -i -r -l $DMENU_LINES \
    -p "$DMENU_PROMPT" \
    -x $DMENU_X \
    -y $DMENU_Y \
    -w $DMENU_WIDTH \
    -h $DMENU_HEIGHT \
    -dim $DMENU_DIM \
    -fn $DMENU_FN \
    -nb $DMENU_NORMBG \
    -nf $DMENU_NORMFG \
    -sb $DMENU_SELBG \
    -sf $DMENU_SELFG
