#!/usr/bin/env bash

source ~/.config/global.conf
source ~/.scripts/monitor-center

# Get centered dimensions based on display resolution
for RES in $SR
do
    center_object $RES
done

DMENU_PROMPT=''
DMENU_FN='tewi'
DMENU_DIM=0.3

DMENU_NORMBG=$BAR_BG
DMENU_NORMFG=$BAR_FG
DMENU_SELBG=$BLUE
DMENU_SELFG=$WHITE

DMENU_WIDTH=300
DMENU_HEIGHT=20
DMENU_X=$(($PX - $DMENU_WIDTH/2))
DMENU_Y=$(($PY - $DMENU_HEIGHT/2))
DMENU_LINES=3

shopt -s nullglob globstar

typeit=0
if [[ $1 == "--type" ]]; then
	typeit=1
	shift
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )
password=$(printf '%s\n' "${password_files[@]}" | dmenu -p "$DMENU_PROMPT" -l $DMENU_LINES -x $DMENU_X -y $DMENU_Y -w $DMENU_WIDTH -h $DMENU_HEIGHT -dim "$DMENU_DIM" -fn $DMENU_FN -nb $DMENU_NORMBG -nf $DMENU_NORMFG -sb $DMENU_SELBG -sf $DMENU_SELFG "$@")
[[ -n $password ]] || exit

if [[ $typeit -eq 0 ]]; then
	pass show -c "$password" 2>/dev/null
else
	xdotool - <<<"type --clearmodifiers -- $(pass show "$password" | head -n 1)"
fi
