#!/usr/bin/env fish

set BG "343D46FF"
set BGLITE "65737EFF"
set FG "C0C5CEFF"
set RED "BF616AFF"
set GRN "A3BE8CFF"

# Suspend notifications
notify-send DUNST_COMMAND_PAUSE

i3lock -n -e --clock \
             --force-clock \
             --timepos="x-100:y-45" \
             --datepos="tx+25:ty+25" \
             --indpos="x+210:y+55" \
             --timestr="%l:%M %p" \
             --datestr="%a, %b %d" \
             --radius=20 \
             --ring-width=2 \
             --veriftext="" \
             --wrongtext="" \
             --line-uses-inside \
             --color=343D46 \
             --textcolor=$FG \
             --timecolor=$FG \
             --datecolor=$FG \
             --separatorcolor=$FG \
             --ringcolor=$FG \
             --keyhlcolor=$BGLITE \
             --bshlcolor=$RED \
             --insidecolor=$BG \
             --insidevercolor=$GRN \
             --insidewrongcolor=$RED \
             --ringcolor=$FG \
             --ringvercolor=$GRN \
             --ringwrongcolor=$RED

# Resume notifications
notify-send DUNST_COMMAND_RESUME
