#!/bin/bash

source ~/.scripts/monitor-center

scrot /tmp/screen.png

# Pixelated Blur BG
convert /tmp/screen.png -scale 10% -scale 1000% -modulate 30,10 /tmp/screen.png

# Smooth Blur BG
#convert /tmp/screen.png -blur 0x3 -modulate 40,20 /tmp/screen.png

if [[ -f $HOME/.lockscreen/lock.png ]]
then
    # Lockscreen image dimensions
    R=$(file ~/.lockscreen/lock.png | grep -o '[0-9]* x [0-9]*')
    RX=$(echo $R | cut -d' ' -f 1)
    RY=$(echo $R | cut -d' ' -f 3)

    # Center image on each monitor
    for RES in $SR
    do
        center_object $RES
        convert /tmp/screen.png $HOME/.lockscreen/lock.png -geometry +$POX+$POY -composite -matte  /tmp/screen.png
    done
fi

i3lock -u -n -i /tmp/screen.png
