#!/bin/env python
import os
from six.moves import input

monitors = input()

monitor_pref = os.environ.get("MONITOR_PREFS", "").split(",")
xargs_cmd = ["xrandr"]
connected_monitors = set()

for monitor in monitors.split(" "):
    if not monitor.endswith("disconnected"):
        mon_name = monitor.split("connected")[0]
        connected_monitors.add(mon_name)

pref_connected = [x for x in monitor_pref if x in connected_monitors]

add_missing = pref_connected + list(
    connected_monitors.difference(set(pref_connected)))

for index, monitor in enumerate(add_missing):
    output_string = "--output {} --auto"
    if index == 0:
        output_string += " --primary "
    elif index > 0:
        output_string += " --right-of " + add_missing[index - 1]
    xargs_cmd.append(output_string.format(monitor))

print(" ".join(xargs_cmd))
