#!/bin/bash
PX=0
PY=0
RX=0
RY=0

function center_object {
    SRX=$(echo $1 | cut -d'x' -f 1)
    SRY=$(echo $1 | cut -d'x' -f 2 | cut -d'+' -f 1)
    SROX=$(echo $1 | cut -d'x' -f 2 | cut -d'+' -f 2)
    SROY=$(echo $1 | cut -d'x' -f 2 | cut -d'+' -f 3)
    PX=$(($SRX/2))
    PY=$(($SRY/2))
    POX=$(($SROX + $SRX/2 - $RX/2))
    POY=$(($SROY + $SRY/2 - $RY/2))
}

# Connected displays
SR=$(xrandr --query | grep ' connected' | grep -Po '\d+x\d+\+\d+\+\d+')
