#!/bin/sh

source ~/.config/global.conf

network() {
    eth=''
    wifi=''
    interfaces=$(ip link | sed -n 's/^[0-9]: \(.*\):.*$/\1/p')
    for interface in $interfaces; do
        if [[ $interface == *"en"* ]] ; then
            eth=$interface
        elif [[ $interface == *"wlp"* ]] ; then
            wifi=$interface
        fi
    done

    lan_state=$(cat /sys/class/net/$eth/operstate 2>&1)
    wifi_state=$(cat /sys/class/net/$wifi/operstate 2>&1)

    if [ "$lan_state" = "up" ]
    then
        ip_addr=$(ip -4 addr show $eth | grep -oP '(?<=inet\s)\d+(\.\d+){3}')
        #popup -e "$(echo "%{F$BLUE}%{F-} $ip_addr")"
        notify-send "$ip_addr"
    elif [ "$wifi_state" = "up" ]
    then
        ip_addr=$(ip -4 addr show $wifi | grep -oP '(?<=inet\s)\d+(\.\d+){3}')
        #popup -e "$(echo "%{Sf}%{F$BLUE}%{F-} $(essid -w $wifi) | $ip_addr")"
        notify-send "$(essid -w $wifi) $ip_addr"
    else
        #popup -e "$(echo "%{F$RED}%{F-} Off")" -w 75
        notify-send "Off"
    fi
}

network
