#!/bin/sh
source ~/.config/global.conf

if [ $(pgrep -cx lemonbar) -gt 1 ] ; then
	printf "%s\n" "The panel is already running."
    while [[ $(pgrep -c "lemonbar") != 0 ]]
    do
        pkill -n -9 "lemonbar"
    done
fi
trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

# Current offset for bar per monitor
CUR_X_OFFSET=0

# Number of monitors
monitor_name=$(bspc query -M)

PANEL_GAP=0

for i in $monitor_name; do
    [ -e "$PANEL_FIFO$i" ] && rm "$PANEL_FIFO$i"
    mkfifo "$PANEL_FIFO$i"

    # Current monitor
    bspc control --subscribe |\
        grep -oE "[Mm]$i[^TM]*[TML]" --line-buffered |\
        while read line; do echo W$line; done \
            > "$PANEL_FIFO$i" &

    # System information
    bar-info > "$PANEL_FIFO$i" &

    # Current monitor width
    CUR_MON_WIDTH=$(bspc query -T -m $i | grep -oE "[0-9]{3,6}" | head -n 1)

    # Pipe inof to Lemonbar
    cat "$PANEL_FIFO$i" | panel-bar | lemonbar -g $(expr $CUR_MON_WIDTH - $(expr $PANEL_GAP + $PANEL_GAP))x15+$(expr $CUR_X_OFFSET + $PANEL_GAP)+$PANEL_GAP -f "$FONT1" -f "$FONT2" -F "$BAR_FG" -B "$BAR_BG"| sh &

    # Increment the x offset for the next monitor.
    CUR_X_OFFSET=$(expr $CUR_X_OFFSET + $CUR_MON_WIDTH )
done

wait
