#!/bin/bash
FONT1="-*-tewi-medium-r-normal-*-11-*-*-*-*-*-*-*"
FONT2="-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1"
BLACK=#FF2C3E50
RED=#FFC0392B
GREEN=#FF27AE60
ORANGE=#FFD35400
YELLOW=#FFF1C40F
BLUE=#FF22A7F0
MAGENTA=#FFE74C3C
CYAN=#FF16A085
WHITE=#FFFFFFFF
DARK=#FF34495E
GREY=#FF586E75
FG=#FFEDDCD3
BG=#FF191919

monitors="`bspc query --monitors | wc -l`"

function statusbar {

    batt() {
        batt_status=$(battery | awk -F' ' '{print $1}')
        batt_level=$(battery | awk -F' ' '{print $2}')
        if [ $batt_status == 'Charging' ] ; then
            echo "%{F$BLUE}%{F-} $batt_level"
        elif [ $batt_level -lt 10 ] ; then
            echo "%{F$ORANGE}%{F-} $batt_level"
        elif [ $batt_level -lt 50 ] ; then
            echo "%{F$BLUE}%{F-} $batt_level"
        elif [ $batt_level -le 100 ] ; then
            echo "%{F$BLUE}%{F-} $batt_level"
        fi
    }

    clock() {
        time=$(/usr/sbin/clock -f "%a %b %d %l:%M %p")
        echo $time
    }

    vol() {
        vol_level=$(volume | awk -F' ' '{print $1}')
        if [ $vol_level == 'off' ] ; then
            vol="$vol_level"
        else
            vol=$(volume | awk -F' ' '{print $2}')
        fi
        echo $vol
    }

    desktops() {
        desktop="`bspc control --get-status`"
        # bspwm state
        wm_info=""
        IFS=':'
        set -- ${desktop#?}
        while [ $# -gt 0 ] ; do
            item=$1
            case $item in
                M*)
                    # active monitor
                    #if [ $monitors -gt 1 ] ; then
                    #    wm_info="$wm_info %{F$RED}%{F-}  "
                    #fi
                    ;;
                m*)
                    # inactive monitor
                    #if [ $monitors -gt 1 ] ; then
                    #    wm_info="$wm_info %{F$GREY}%{F-}  "
                    #fi
                    ;;
                O*)
                    # focused occupied desktop
                    wm_info="${wm_info} %{U$BLUE}%{+u}%{-u}"
                    ;;
                F*)
                    # focused free desktop
                    wm_info="${wm_info} %{U$BLUE}%{+u}%{-u}"
                    ;;
                U*)
                    # focused urgent desktop
                    wm_info="${wm_info} %{U$MAGENTA}%{+u}%{-u}"
                    ;;
                o*)
                    # occupied desktop
                    wm_info="${wm_info} %{U$WHITE}%{+u}  %{-u}"
                    ;;
                f*)
                    # free desktop
                    wm_info="${wm_info} %{U$GREY}%{+u}  %{-u}"
                    ;;
                u*)
                    # urgent desktop
                    wm_info="${wm_info} %{U$MAGENTA}%{+u}  %{-u}"
                    ;;
                L*)
                    # layout
                    ;;
            esac
            shift
        done
        printf "%s\n" "${wm_info}"
    }

    networks() {
        LAN_STATE=`cat /sys/class/net/enp0s25/operstate`
        WIFI_STATE=`cat /sys/class/net/wlp3s0/operstate`

        if [ "$LAN_STATE" = "up" ]
        then
            text="%{F$BLUE}%{F-} lan"
        elif [ "$WIFI_STATE" = "up" ]
        then
            text="%{F$BLUE}%{F-} `essid -w wlp3s0`"
        else
            text="off"
        fi

        network="$text"
        echo $network
    }

    echo " $(desktops) %{c}$(clock)%{r}$(networks)%{F$BLUE}  %{F-}$(vol) $(batt)%% "
}

while true
do
    echo "$(statusbar)"
    sleep 0.5
done | lemonbar -g x15 -f "$FONT1" -f "$FONT2" -B "$BG" -F "$FG" -p &
