#!/bin/sh

source ~/.config/global.conf

TOGGLE_FILE='/tmp/toggle-panel'
if [ ! -e "$TOGGLE_FILE" ] ; then
    echo -n 0 > $TOGGLE_FILE
fi

while read -r line ; do

    if [[ $(< $TOGGLE_FILE) -eq 1 ]] ; then
        TOGGLE=true
        TOGGLE_ICON="›"
    else
        TOGGLE=false
        TOGGLE_ICON="‹"
    fi

    case $line in
    S*)
        sys_infos="${line#?}"
    ;;
    W*)
        wm_info=""
        IFS=':'
        set -- ${line#?}
        while [ $# -gt 0 ] ; do
            item=$1
            name=${item#?}
            case $item in
                O*) wm_info="${wm_info} %{U$BLUE}%{+u}%{-u}";;
                F*) wm_info="${wm_info} %{U$BLUE}%{+u}%{-u}";;
                U*) wm_info="${wm_info} %{U$RED}%{+u}%{-u}";;
                o*) wm_info="${wm_info} %{U$WHITE}%{+u}  %{-u}";;
                f*) wm_info="${wm_info} %{U$GREY}%{+u}  %{-u}";;
                u*) wm_info="${wm_info} %{U$RED}%{+u}  %{-u}";;
            esac
            shift
        done
        wm_info="$wm_info "
    ;;
    esac
    printf "%s\n" "%{l} %{F$BLUE}%{A3:shutdown -h now:}%{A3}%{F-}$wm_info %{r}%{A:toggle-panel:}$TOGGLE_ICON$sys_infos%{A}"
done
