#! /bin/sh
#
# Example panel for LemonBoy's bar

while read -r line ; do
    case $line in
        T*)
            title="%{A:launcher:} Fedora %{A}"
            ;;
        W*)
            wm_infos="%{c}${line#?}"
            ;;
        S*)
            sys_infos="%{r}${line#?}%{F-}"
            ;;
    esac
    printf "%s\n" "$title$wm_infos$sys_infos"
done
