#!/bin/bash

# BATTERY ICONS:
#      

BATT=`upower -d | grep percentage | awk '{print $2}' | awk '{printf("%d\n",$1 + 0.5)}'`
STATUS=`upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep state | awk '{print $2}'`

# Set Icon
icon=""
if [[ $STATUS != "discharging" ]]; then
	icon="⮎"
elif [[ $BATT -lt 10 ]]; then
	icon="⮐"
elif [[ $BATT -lt 60 ]]; then
	icon="⮑"
else
	icon="⮏"
fi

echo "%{F#FF54ADCD}$icon %{F-}%$BATT"
