#!/bin/sh
source ~/.config/global.conf

cur_mon=$(bspc query -T -m focused | jq '.["focusedDesktopName"]' | egrep -o "[0-9]")
cur_mon_indx=$(expr $cur_mon - 1)

monitor_width=$(bspc query -T -m primary | jq '.["rectangle"]["width"]')

barname="lemon-pop"
sleep=2

width=150
height=40
xoffset=$(expr $monitor_width - $(expr $width + 25))
yoffset=25

bg="$DARK_GREY"
fg="$BAR_FG"

font1="$FONT1"
font2="$FONT2"

# Options

while getopts "w:h:b:f:n:s:e:" opt; do
    case $opt in
        w) width="$OPTARG" ;;
        h) height="$OPTARG" ;;
        b) bg="$OPTARG" ;;
        f) fg="$OPTARG" ;;
        n) barname="$OPTARG" ;;
        s) sleep="$OPTARG" ;;
        e) echo="$OPTARG" ;;
    esac
done

# Start bar

# Kill previous notifications
ps -ef | awk -v name="$barname" '$0 ~ name {print $2}' | xargs kill 2>/dev/null

# Echo notification
(echo "%{c} $echo %{c}"; sleep $sleep) |

# Pipe to bar
lemonbar -n "$barname" -d -g "$width"x"$height+$xoffset+$yoffset" -f "$font1" -f "$font2" -B "$bg" -F "$fg"
