#!/bin/env fish

# Output format
function info --description 'Info logging wrapper'
    echo -e "\e[34m:: $argv\e[0m"
end
function warning
    echo -e "\e[33m:: $argv\e[0m"
end
function error
    echo -e "\e[31m:: $argv\e[0m"
end

# Cannot run as root user
test (id -u) -gt 0; or error "This script cannot be run as root."

# Update Cached sudo credentials
info "Updating cached sudo credentials"
sudo -v

# Check for pacaur to begin installing pkgs, else try installing it
if (command -v pacaur)
    info "Installing from pkgs file"
    pacaur -S (cat ~/.dotfiles/scripts/pkgs | tr '\n' ' ') --needed --devel --noconfirm --noedit
else
    warning "Pacaur not installed, trying to install..."
    sh ~/.dotfiles/scripts/install-pacaur
end

info "Finished installing packages"
