#!/bin/sh

echo "Installing from depends.txt:"
if [ $(which pacaur) ]; then
    for package in $(cat ./depends); do
        pacaur -S $package --needed --devel
    done
else
    echo "Please install pacaur"
fi
