#!/bin/zsh

autoload -U colors
colors

echo Installing from depends...\n
if [ $(which pacaur) ]; then
    pacaur -S $(cat ~/.dotfiles/scripts/depends | tr '\n' ' ') --needed --devel --noconfirm
else
    echo $fg[red]Please install Pacaur first.${reset_color}
fi
